openapi: 3.0.3
info:
  title: Trinity Cloud - API 3.0
  description: |-
    Welcome to Trinity Cloud's API Documentation

    This API is designed to empower Horizon Christian School with seamless access to the custom tools developed by Trinity Cloud. Our API offers a robust and secure interface, enabling efficient integration
    with your existing systems. Through this OpenAPI Swagger documentation, you'll find comprehensive details on how to utilize our API, including endpoints, request parameters, and response formats. Whether
    you're managing IT resources, automating tasks, or enhancing your school's digital infrastructure, our API is built to support your needs with reliability and ease. Explore the capabilities and start
    integrating today!
  contact:
    email: tickets@trinitycloud.com.au
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
servers:
  - url: https://api.trincloud.cc/v1
tags:
  - name: syncer
    description: Getting and Setting settings for Canvas Sync Script

paths:
  /get_syncer:
    get:
      tags:
        - syncer
      summary: get sync settings object
      description: Returns a syncer opject
      operationId: getsyncsettings
      responses:
        '200':
          description: OK
        '404':
          description: API not found.
        default:
          description: Unexpected error
  /set_syncer:
    post:
      tags:
        - syncer
      summary: Updates a pet in the store with form data
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                enabled:
                  type: boolean
                  example: True
                newterm:
                  type: string
                  example: 24.01
      responses:
        '200':
          description: Created
        '404':
          description: API not found.
        default:
          description: Unexpected error
components:
  schemas:
    get_syncer:
      type: object
      properties:
        enabled:
          type: string
          example: True
        newterm:
          type: string
          example: 24.01
    set_syncer:
      type: object
      properties:
        enabled:
          type: string
          example: True
        newterm:
          type: string
          example: 24.01